# Generated by Django 2.0.7 on 2020-03-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
